global:
  resolve_timeout: 5m
  slack_api_url: "https://hooks.slack.com/services/your/slack/webhook"

route:
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: "slack-notifications"
  routes:
    - match:
        severity: critical
      receiver: "slack-critical"
      group_wait: 10s
      repeat_interval: 1h

receivers:
  - name: "slack-notifications"
    slack_configs:
      - channel: "#mcp-alerts"
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        footer: '{{ template "slack.default.footer" . }}'

  - name: "slack-critical"
    slack_configs:
      - channel: "#mcp-critical"
        send_resolved: true
        title: '[CRITICAL] {{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        footer: '{{ template "slack.default.footer" . }}'

templates:
  - "/etc/alertmanager/template/*.tmpl"

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "job"]
