global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/prometheus-rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "mcp"
    static_configs:
      - targets: ["host.docker.internal:9464"]
    metrics_path: "/metrics"

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
    metrics_path: "/metrics"
